import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Bodoni_Moda } from "next/font/google";
import "./globals.css";

const inter = Bodoni_Moda({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
